# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Mountain.create(name: 'Washington', elevation: 6288)
Mountain.create(name: 'Adams', elevation: 5774)
Mountain.create(name: 'Jefferson', elevation: 5712)
Mountain.create(name: 'Monroe', elevation: 5384)
Mountain.create(name: 'Madison', elevation: 5367)
Mountain.create(name: 'Lafayette', elevation: 5260)
Mountain.create(name: 'Lincoln', elevation: 5089)
Mountain.create(name: 'South Twin', elevation: 4902)
Mountain.create(name: 'Carter Dome', elevation: 4832)
Mountain.create(name: 'Moosilauke', elevation: 4802)
Mountain.create(name: 'Eisenhower', elevation: 4780)
Mountain.create(name: 'North Twin', elevation: 4761)
Mountain.create(name: 'Carrigain', elevation: 4700)
Mountain.create(name: 'Bond', elevation: 4698)
Mountain.create(name: 'Middle Carter', elevation: 4610)
Mountain.create(name: 'West Bond', elevation: 4540)
Mountain.create(name: 'Garfield', elevation: 4500)
Mountain.create(name: 'Liberty', elevation: 4459)
Mountain.create(name: 'South Carter', elevation: 4430)
Mountain.create(name: 'Wildcat, A peak', elevation: 4422)
Mountain.create(name: 'Hancock', elevation: 4420)
Mountain.create(name: 'South Kinsman', elevation: 4358)
Mountain.create(name: 'Field', elevation: 4340)
Mountain.create(name: 'Osceola', elevation: 4340)
Mountain.create(name: 'Flume', elevation: 4328)
Mountain.create(name: 'South Hancock', elevation: 4319)
Mountain.create(name: 'Pierce', elevation: 4310)
Mountain.create(name: 'North Kinsman', elevation: 4293)
Mountain.create(name: 'Willey', elevation: 4285)
Mountain.create(name: 'Bondcliff', elevation: 4265)
Mountain.create(name: 'Zealand', elevation: 4260)
Mountain.create(name: 'North Tripyramid', elevation: 4180)
Mountain.create(name: 'Cabot', elevation: 4170)
Mountain.create(name: 'East Osceola', elevation: 4136)
Mountain.create(name: 'Middle Tripyramid', elevation: 4180)
Mountain.create(name: 'Cannon', elevation: 4100)
Mountain.create(name: 'Hale', elevation: 4054)
Mountain.create(name: 'Jackson', elevation: 4052)
Mountain.create(name: 'Tom', elevation: 4051)
Mountain.create(name: 'Wildcat, D peak', elevation: 4050)
Mountain.create(name: 'Moriah', elevation: 4059)
Mountain.create(name: 'Passaconaway', elevation: 4039)
Mountain.create(name: 'Owl''s Head', elevation: 4025)
Mountain.create(name: 'Galehead', elevation: 4024)
Mountain.create(name: 'Whiteface', elevation: 4020)
Mountain.create(name: 'Waumbek', elevation: 4006)
Mountain.create(name: 'Isolation', elevation: 4004)
Mountain.create(name: 'Tecumseh', elevation: 4003)
